name: run-rubocop-check
run-name: rubocop
on: [push]
jobs:
  run-rubocop:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1.2'

      - name: Install dependencies
        run: bundle install

      - name: Run rubocop
        run: bundle exec rubocop